version: '3.3'

services:

    mysql_db:
            container_name: ${DOCKER_CONTAINER_PREFIX}_mysql_db
            restart: unless-stopped
            image: mysql:5.7
            command: --innodb_use_native_aio=0
            environment:
                MYSQL_DATABASE: ${DB_DATABASE}
                MYSQL_USER: ${DB_USERNAME}
                MYSQL_PASSWORD: ${DB_PASSWORD}
                MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            ports:
                - ${DB_EXPOSE_PORT}:3306
            volumes:
                - ./mysql_db:/var/lib/mysql
