version: '3.3'

services:

    nginx:
        image: ${DOCKER_IMAGE_PREFIX}_nginx:${DOCKER_TAG}
        container_name: ${DOCKER_CONTAINER_PREFIX}_nginx
        restart: always
        build:
            context: ./../
            dockerfile: ./devops/nginx/Dockerfile
        volumes:
            - ./..:/var/www/html
        links:
            - php_fpm:php_fpm
        ports:
            - ${APP_REST_PORT}:80
        env_file:
          - ./../.env
        environment:
            - REMOTE_DEBUG_HOST

    php_fpm:
        image: ${DOCKER_IMAGE_PREFIX}_php_fpm:${DOCKER_TAG}
        container_name: ${DOCKER_CONTAINER_PREFIX}_php_fpm
        restart: always
        build:
            context: ./../
            dockerfile: ./devops/php_fpm/Dockerfile
        volumes:
            - ./..:/var/www/html
        env_file:
          - ./../.env
        environment:
            - DB_PORT
            - DB_HOST
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
            - PHP_IDE_CONFIG
            - REMOTE_DEBUG_HOST
            - REMOTE_DEBUG_PORT
